<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="P3B-6KKFNK2" ignored="1" name="Test" tests="19" failures="5" timestamp="2019-12-10T16:36:38 IST" time="30.875" errors="0">
  <testcase name="Test1" time="0.025" classname="testngfeatures.DemoAssertions"/>
  <testcase name="Test2" time="0.016" classname="testngfeatures.DemoAssertions">
    <failure type="java.lang.AssertionError" message="Error msg- 20 greater than 18 did not expect to find [false] but found [true]">
      <![CDATA[java.lang.AssertionError: Error msg- 20 greater than 18 did not expect to find [false] but found [true]
at testngfeatures.DemoAssertions.Test2(DemoAssertions.java:19)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase name="Test3" time="0.016" classname="testngfeatures.DemoAssertions">
    <failure type="java.lang.AssertionError" message="expected [Hi] but found [Hello]">
      <![CDATA[java.lang.AssertionError: expected [Hi] but found [Hello]
at testngfeatures.DemoAssertions.Test3(DemoAssertions.java:26)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- Test3 -->
  <testcase name="Test4" time="0.0" classname="testngfeatures.DemoAssertions"/>
  <testcase name="Test5" time="0.0" classname="testngfeatures.DemoAssertions"/>
  <testcase name="Test6" time="0.0" classname="testngfeatures.DemoAssertions">
    <failure type="java.lang.AssertionError" message="expected object to not be null">
      <![CDATA[java.lang.AssertionError: expected object to not be null
at testngfeatures.DemoAssertions.Test6(DemoAssertions.java:44)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- Test6 -->
  <testcase name="Test7" time="0.0" classname="testngfeatures.DemoAssertions">
    <failure type="java.lang.AssertionError" message="Intentional Fail">
      <![CDATA[java.lang.AssertionError: Intentional Fail
at testngfeatures.DemoAssertions.Test7(DemoAssertions.java:49)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- Test7 -->
  <testcase name="f" time="0.0" classname="testngfeatures.ExecutionSeq"/>
  <testcase name="f" time="10.914" classname="testngfeatures.LoginMercury"/>
  <testcase name="f" time="0.002" classname="testngfeatures.NewTestdemonew"/>
  <testcase name="login" time="0.001" classname="testngfeatures.DemoDataprovider"/>
  <testcase name="login" time="0.001" classname="testngfeatures.DemoDataprovider"/>
  <testcase name="test1" time="0.011" classname="testngfeatures.DemoSoftAssert">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [hi] but found [hello],
	Error msg: both values are same did not expect to find [10] but found [10]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [hi] but found [hello],
Error msg: both values are same did not expect to find [10] but found [10]
at testngfeatures.DemoSoftAssert.test1(DemoSoftAssert.java:19)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="openbrowser" time="0.002" classname="testngfeatures.MercuryApplication"/>
  <testcase name="openurl" time="0.01" classname="testngfeatures.MercuryApplication"/>
  <testcase name="Login" time="0.001" classname="testngfeatures.MercuryApplication"/>
  <testcase name="bookFlight" time="0.003" classname="testngfeatures.MercuryApplication"/>
  <testcase name="closebrowser" time="0.001" classname="testngfeatures.MercuryApplication"/>
  <testcase name="logout" time="0.001" classname="testngfeatures.MercuryApplication"/>
  <testcase name="searchFlight" time="0.0" classname="testngfeatures.MercuryApplication">
    <ignored/>
  </testcase> <!-- searchFlight -->
</testsuite> <!-- Test -->
